// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52YuHn0soXHUUGXV3OlV71T4xIcu7ns4',
    appId: '1:410473791154:web:48bdca10f06e394da853ab',
    messagingSenderId: '410473791154',
    projectId: 'you-matter-5b83d',
    authDomain: 'you-matter-5b83d.firebaseapp.com',
    storageBucket: 'you-matter-5b83d.firebasestorage.app',
    measurementId: 'G-VJR7KQNZD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABN8i7iC_5kK4Zs5G02JsoKOPAv3nWkMM',
    appId: '1:410473791154:android:def9d1efca999d18a853ab',
    messagingSenderId: '410473791154',
    projectId: 'you-matter-5b83d',
    storageBucket: 'you-matter-5b83d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8iU9oZR7BCRh6vLzpEb1gMzYXPbGC8Hk',
    appId: '1:410473791154:ios:bcf36022a95f28f5a853ab',
    messagingSenderId: '410473791154',
    projectId: 'you-matter-5b83d',
    storageBucket: 'you-matter-5b83d.firebasestorage.app',
    iosBundleId: 'com.example.youMatterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8iU9oZR7BCRh6vLzpEb1gMzYXPbGC8Hk',
    appId: '1:410473791154:ios:bcf36022a95f28f5a853ab',
    messagingSenderId: '410473791154',
    projectId: 'you-matter-5b83d',
    storageBucket: 'you-matter-5b83d.firebasestorage.app',
    iosBundleId: 'com.example.youMatterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52YuHn0soXHUUGXV3OlV71T4xIcu7ns4',
    appId: '1:410473791154:web:11a13a90a1e858b3a853ab',
    messagingSenderId: '410473791154',
    projectId: 'you-matter-5b83d',
    authDomain: 'you-matter-5b83d.firebaseapp.com',
    storageBucket: 'you-matter-5b83d.firebasestorage.app',
    measurementId: 'G-WMW2Z79VZ2',
  );
}
